linked_in:
  email: ""
  password: ""
  phone_num: "555-555-5555"
  resume_path: ""

indeed:
  email: ""
  password: ""
  phone_num: "555-555-5555"
  resume_path: ""

settings:
  #how many seconds between click/submit actions. increase if getting
  # a "spinner" related error
  load_time: 2
  follow_companies: false
  testing: false
  filters:
    - 'Apple'
    - 'Facebook'
    - 'Uber'
    - 'Groupon'
    - 'Google'
    - 'LinkedIn'
    - 'Amazon'
    - 'Ebay'
    - 'Senior'
    - 'Backend'
    - 'Sr'
    - 'Sr.'
