linked_in:
  email: ""
  password: ""
  phone_num: "555-555-5555"
  resume_path: "/absolute/path/your_resume.pdf"

settings:
  load_time: 1
  testing: false
  filters:
    - 'keywords'
    - 'you'
    - 'dont'
    - 'want'
