linked_in:
  email: ""
  password: ""
  phone_num: "555-555-5555"
  resume_path: "/absolute/path/your_resume.pdf"

settings:
  #how many seconds between click/submit actions. increase if getting
  # a "spinner" related error
  load_time: 2
  follow_companies: false
  testing: false
  filters:
    - 'keywords'
    - 'you'
    - 'dont'
    - 'want'
