linked_in:
  email: "aylanismello@gmail.com"
  password: "L08181991d"
  phone_num: "415-608-8533"
  resume_path: "/Users/aylanmello/Documents/A.A/job/aylanmello_resume.pdf"

job_bot:
  batch_num: 5
  load_time: 1
