linked_in:
  email: ""
  password: ""
  phone_num: "555-555-5555"
  resume_path: ""

settings:
  load_time: 1
  testing: false
  filters:
    - 'Apple'
    - 'Facebook'
    - 'Uber'
    - 'Groupon'
    - 'Google'
    - 'LinkedIn'
    - 'Amazon'
    - 'Ebay'
    - 'Senior'
    - 'Backend'
    - 'Sr'
    - 'Sr.'
