linked_in:
  email: "email"
  password: "password"
  phone_num: "555-555-5555"
  resume_path: "/path/to/your/resume.pdf"
  follow_companies: false

zip_recruiter:
  email: "email"
  password: "password"
  batch_num: 2

settings:
  #how many seconds between click/submit actions. increase if getting
  # a "spinner" related error
  load_time: 2
  testing: false
  filters:
    - 'keywords'
    - 'you'
    - 'dont'
    - 'want'
